/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CommitmentsIdRouteImport } from './routes/commitments.$id'
import { Route as ResolutionIdRouteImport } from './routes/resolution.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitmentsIdRoute = CommitmentsIdRouteImport.update({
  id: '/commitments/$id',
  path: '/commitments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolutionIdRoute = ResolutionIdRouteImport.update({
  id: '/resolution/$id',
  path: '/resolution/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/commitments/$id': typeof CommitmentsIdRoute
  '/resolution/$id': typeof ResolutionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/commitments/$id': typeof CommitmentsIdRoute
  '/resolution/$id': typeof ResolutionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/commitments/$id': typeof CommitmentsIdRoute
  '/resolution/$id': typeof ResolutionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/dashboard'
    | '/profile'
    | '/commitments/$id'
    | '/resolution/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/dashboard'
    | '/profile'
    | '/commitments/$id'
    | '/resolution/$id'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/dashboard'
    | '/profile'
    | '/commitments/$id'
    | '/resolution/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  CommitmentsIdRoute: typeof CommitmentsIdRoute
  ResolutionIdRoute: typeof ResolutionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commitments/$id': {
      id: '/commitments/$id'
      path: '/commitments/$id'
      fullPath: '/commitments/$id'
      preLoaderRoute: typeof CommitmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolution/$id': {
      id: '/resolution/$id'
      path: '/resolution/$id'
      fullPath: '/resolution/$id'
      preLoaderRoute: typeof ResolutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  CommitmentsIdRoute: CommitmentsIdRoute,
  ResolutionIdRoute: ResolutionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
